name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        package_name:
          - npm-pack-install-mre
          - "@google-labs/breadboard-cli"
        node:
          - 20
        npm:
          - 10.2.1
          # - 10.2.2
          # - 10.2.3
          # - 10.2.4
          # - 10.2.5
          # - 10.3.0
          # - 10.4.0
          - 10.5.0
        command:
          - npm install -g $(npm pack)
          - npm install -g $(npm pack) && (cd ~ && npx ${PACKAGE_NAME} -- --help)
          - npm pack && npm install -g $(find . -name $CLEAN_PACKAGE_NAME-*.tgz)
          - npm pack && npm install -g $(find . -name $CLEAN_PACKAGE_NAME-*.tgz) && (cd ~ && npx ${PACKAGE_NAME} -- --help)
          - npm run npm:pack:install
          - npm run npm:test:pack
          - npm run wireit:pack:install
          - npm run wireit:test:pack
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - run: set -u

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}

      - run: npm install -g npm@${{ matrix.npm }}
      - run: npm install
      - run: npm --version
      - run: npm config set loglevel verbose

      - run: npm pkg set name=${{ matrix.package_name }}

      - run: |
          export PACKAGE_NAME=$(npm pkg get name | tr -d '\"')
          echo $PACKAGE_NAME

          export CLEAN_PACKAGE_NAME=$(echo $PACKAGE_NAME | sed 's/@//;s/\//-/')
          echo $CLEAN_PACKAGE_NAME

          exec ${{ matrix.command }}
