name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node:
          - 20
        npm:
          - 10.2.1
          # - 10.2.2
          # - 10.2.3
          # - 10.2.4
          # - 10.2.5
          # - 10.3.0
          # - 10.4.0
          - 10.5.0
        command:
          - npm install -g $(npm pack)
          - npm install -g $(npm pack) && (cd ~ && npx npm-pack-install-mre --help)
          - npm pack && npm install -g $(find . -name 'google-labs-breadboard-cli-*.tgz')
          - npm pack && npm install -g $(find . -name 'google-labs-breadboard-cli-*.tgz') && (cd ~ && npx npm-pack-install-mre --help)
          - npm run npm:pack:install
          - npm run npm:test:pack
          - npm run wireit:pack:install
          - npm run wireit:test:pack
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}

      - run: npm install -g npm@${{ matrix.npm }}
      - run: npm --version
      - run: npm config set loglevel verbose
      - run: exec ${{ matrix.command }}
